Added Splash Screen and App icon
nathan-wick/nutrition-ai pull request #91
Opened 2024-02-08 15:25 UTC by ModupeD

Updated App title and ReadMe with from Nutrition AI to NutriMind.
Updated App Logo and Splash Screen with new App Logo
![app splash screen](https://github.com/nathan-wick/nutrition-ai/assets/69601432/4cc0abfc-ff2b-4abd-8a69-bfb9fbdb4f89)

![app icon logo](https://github.com/nathan-wick/nutrition-ai/assets/69601432/45ac4b4a-3455-4749-88c4-e3ce88593bd3)

2024-02-09 00:47 UTC, nathan-wick requested changes
Looks AWESOME! I made one small request, let me know what you think. Other than that, this should be good to merge.

2024-02-09 00:47 UTC, nathan-wick commented on nutrition_ai/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
For these images, could we zoom in and center the logo? That way there's less white space.

2024-02-09 13:24 UTC, ModupeD commented on nutrition_ai/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
i like it, thank you. I learned something new

2024-02-11 03:33 UTC, ModupeD reviewed
This is good. Thank you

2024-02-13 03:08 UTC, nathan-wick approved these changes
Looks great! Thank you!

2024-02-13 03:10 UTC, merged